config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit'
  delete 'books/:id' => 'books#destroy', as: 'destroy'
  patch 'books/:id' => 'books#update', as: 'update'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash.now[:alert] = "Book wasn't successfully created."
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
    flash[:notice] = "Book was successfully destroyed."
  end
  
  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
       flash[:notice2] = "Book was successfully updated."
       redirect_to book_path(@book.id)
     else
      flash.now[:alert] = "Book wasn't successfully created."
      render :edit
     end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    render 'top'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
    <%= @book.errors.count %>"errors prohibited this book from being saved:"
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
<%= form_with model: @book, url: update_path(@book.id),method: :patch do |f| %>
<div>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
</div>
  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to 'Show',book_path %>
|
<%= link_to 'Back','/books' %>

app/views/books/index.html.erb
<h1>Books</h1>
  <table>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><span><%= book.title %></span></td>
        <td><span><%= book.body %></span></td>
        <td>
        <%= link_to 'Show', book_path(book.id) %>
        <%= link_to 'Edit', edit_path(book.id) %>
        <%= link_to 'Destroy',destroy_path(book.id),method: :delete, "data-confirm" => "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </table>
  
  <h2>New book</h2>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

 <%= form_with model: @book do |f| %>
  <div>
    <h4>Title</h4><%= f.text_field :title %>
    <h4>Body</h4><%= f.text_area :body %>
  </div>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<table>
  <tbody>
    <tr>
      <td>Title:</td>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <td>Body:</td>
      <td><%= @book.body %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_path(@book.id) %>
|
<%= link_to 'Back', '/books' %>

app/views/homes/top.html.erb
<h2>ようこそBookersへ！</h2>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to 'start', '/books' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
    <div class=flash>
     <% flash.each do |message_type, message| %>
       <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
    </div>
      <%= yield %>
    </main>
  </body>
</html>